version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docsify
    image: docsify
    restart: always
    environment:
      - HOST_USER_ID=1000
    volumes:
      - ${DOCS_PATH}:/docs
    ports:
      - "3000:3000"